### ISSUE TITLE
Weapon items cannot be opened

### ISSUE THREAD

**Issue by abacus-tabletop-games** [Forelius/fade-compendiums#1] opened 2024-12-16 16:11 UTC
Using Fantastic Depths 0.6.10 and compendium 0.7.2

When clicking on a weapon item, nothing opens. It happens whether in compendium, imported as an item (using right-click) and on PC sheet.

Thanks!

**Comment by Forelius** [comment] 2024-12-16 18:17
> Using Fantastic Depths 0.6.10 and compendium 0.7.2
> When clicking on a weapon item, nothing opens. It happens whether in compendium, imported as an item (using right-click) and on PC sheet.

I'm not able to reproduce this issue. What browser are you using or is it the desktop client?
Try opening the debug console, and then click to open the item and post any errors that are generated.

**Comment by abacus-tabletop-games** [comment] 2024-12-16 19:38
I'm using the desktop client. Here is the error: 
![image](https://github.com/user-attachments/assets/8e678806-146c-4c8e-8541-6009664e50f9)
![image](https://github.com/user-attachments/assets/144908eb-40d0-4470-8171-6ec395cca279)

**Comment by Forelius** [comment] 2024-12-16 21:02
Do you have weapon mastery disabled? I think I figured out what happened.

**Comment by Forelius** [comment] 2024-12-16 21:17
Thanks for bringing this to my attention. It was an issue with the main project and has been fixed with fantastic-depths release v06.11, or it least it should be fixed.

**Closed as completed by Forelius** 2024-12-16 21:17 UTC
